#!/usr/bin/env python3
"""
Migration Script: Transition to OAuth2 Authentication

This script helps migrate from the non-OAuth version of Gemini Chat
to the OAuth2-enabled version.
"""

import os
import sqlite3
import shutil
import json
from datetime import datetime
from pathlib import Path

def backup_existing_data():
    """Backup existing chat history and configuration"""
    print("🔄 Creating backup of existing data...")
    
    backup_dir = Path("backup_" + datetime.now().strftime("%Y%m%d_%H%M%S"))
    backup_dir.mkdir(exist_ok=True)
    
    # Backup chat history database
    if os.path.exists("chat_history.db"):
        shutil.copy2("chat_history.db", backup_dir / "chat_history.db")
        print(f"✅ Backed up chat_history.db to {backup_dir}")
    
    # Backup .env file
    if os.path.exists(".env"):
        shutil.copy2(".env", backup_dir / ".env")
        print(f"✅ Backed up .env to {backup_dir}")
    
    # Backup allowed_context directory
    if os.path.exists("allowed_context"):
        shutil.copytree("allowed_context", backup_dir / "allowed_context")
        print(f"✅ Backed up allowed_context to {backup_dir}")
    
    return backup_dir

def update_database_schema():
    """Update database schema to include user associations"""
    print("🔄 Updating database schema...")
    
    if not os.path.exists("chat_history.db"):
        print("⚠️  No existing chat_history.db found. New database will be created.")
        return
    
    try:
        with sqlite3.connect("chat_history.db") as conn:
            cursor = conn.cursor()
            
            # Check if user_id column exists
            cursor.execute("PRAGMA table_info(history)")
            columns = [column[1] for column in cursor.fetchall()]
            
            if 'user_id' not in columns:
                # Add user_id column to existing history table
                cursor.execute("ALTER TABLE history ADD COLUMN user_id TEXT")
                print("✅ Added user_id column to history table")
            else:
                print("✅ Database schema already updated")
            
            conn.commit()
            
    except Exception as e:
        print(f"❌ Error updating database schema: {e}")
        return False
    
    return True

def create_oauth_env_file():
    """Create OAuth2 environment configuration"""
    print("🔄 Setting up OAuth2 configuration...")
    
    # Read existing .env if it exists
    existing_config = {}
    if os.path.exists(".env"):
        with open(".env", "r") as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    key, value = line.strip().split("=", 1)
                    existing_config[key] = value
    
    # Create new .env with OAuth2 settings
    oauth_config = {
        "GOOGLE_API_KEY": existing_config.get("GOOGLE_API_KEY", "your_google_api_key_here"),
        "SECRET_KEY": existing_config.get("SECRET_KEY", "your_super_secret_key_change_this_in_production"),
        "OAUTH2_PROVIDER": "google",
        "GOOGLE_CLIENT_ID": "your_google_client_id.apps.googleusercontent.com",
        "GOOGLE_CLIENT_SECRET": "your_google_client_secret",
        "ENABLE_ROLE_BASED_ACCESS": "true",
        "DEFAULT_USER_ROLE": "user",
        "ADMIN_EMAILS": "admin@example.com",
        "ENABLE_RATE_LIMITING": "true",
        "RATE_LIMIT_PER_USER": "100"
    }
    
    # Write new .env file
    with open(".env.oauth", "w") as f:
        f.write("# Gemini Chat OAuth2 Configuration\n")
        f.write("# Generated by migration script\n\n")
        
        for key, value in oauth_config.items():
            f.write(f"{key}={value}\n")
        
        f.write("\n# Instructions:\n")
        f.write("# 1. Set up OAuth2 credentials with your provider\n")
        f.write("# 2. Update the OAuth2 client ID and secret above\n")
        f.write("# 3. Add admin email addresses\n")
        f.write("# 4. Rename this file to .env\n")
    
    print("✅ Created .env.oauth with OAuth2 configuration")
    print("📝 Please update OAuth2 credentials and rename to .env")

def install_oauth_dependencies():
    """Install OAuth2 dependencies"""
    print("🔄 Installing OAuth2 dependencies...")
    
    try:
        import subprocess
        result = subprocess.run([
            "pip", "install", 
            "Flask-Login==0.6.3",
            "Authlib==1.3.0", 
            "requests-oauthlib==1.3.1",
            "cryptography==41.0.7"
        ], capture_output=True, text=True)
        
        if result.returncode == 0:
            print("✅ OAuth2 dependencies installed successfully")
        else:
            print(f"⚠️  Warning: Some dependencies may not have installed correctly")
            print(f"Error: {result.stderr}")
            print("Please run: pip install -r requirements-oauth.txt")
    
    except Exception as e:
        print(f"⚠️  Could not automatically install dependencies: {e}")
        print("Please run: pip install -r requirements-oauth.txt")

def create_migration_summary():
    """Create migration summary and next steps"""
    summary = """
# Migration to OAuth2 Complete! 🎉

## What was done:
1. ✅ Backed up existing data
2. ✅ Updated database schema
3. ✅ Created OAuth2 configuration template
4. ✅ Installed OAuth2 dependencies

## Next Steps:

### 1. Set up OAuth2 Provider
Choose one of the following:

**Google OAuth2:**
1. Go to Google Cloud Console (https://console.cloud.google.com/)
2. Create OAuth2 credentials
3. Add redirect URI: http://localhost:5000/auth/callback

**GitHub OAuth2:**
1. Go to GitHub Settings > Developer settings > OAuth Apps
2. Create new OAuth App
3. Set callback URL: http://localhost:5000/auth/callback

### 2. Update Configuration
1. Edit .env.oauth file with your OAuth2 credentials
2. Add admin email addresses
3. Rename .env.oauth to .env

### 3. Test the Application
1. Run: python app_with_oauth.py
2. Navigate to http://localhost:5000
3. Test login with your OAuth2 provider

### 4. Verify Migration
- Check that existing chat history is preserved
- Verify that context files are accessible
- Test all features with authentication

## Files Created:
- .env.oauth (OAuth2 configuration template)
- backup_YYYYMMDD_HHMMSS/ (backup directory)

## Important Notes:
- Your original data has been backed up
- The original app.py still works without OAuth2
- Use app_with_oauth.py for the OAuth2 version
- All existing chat history will be preserved

## Troubleshooting:
If you encounter issues:
1. Check the backup directory for original files
2. Review README_OAUTH2.md for detailed setup instructions
3. Verify OAuth2 provider configuration
4. Check .env file for correct credentials

## Support:
For help with OAuth2 setup, refer to:
- README_OAUTH2.md (detailed documentation)
- .env.oauth.template (configuration examples)
- test_oauth2.py (test examples)
"""
    
    with open("MIGRATION_SUMMARY.md", "w") as f:
        f.write(summary)
    
    print("✅ Created MIGRATION_SUMMARY.md with next steps")

def main():
    """Main migration function"""
    print("🚀 Starting migration to OAuth2 authentication...")
    print("=" * 50)
    
    # Step 1: Backup existing data
    backup_dir = backup_existing_data()
    
    # Step 2: Update database schema
    if not update_database_schema():
        print("❌ Database migration failed. Check backup and try again.")
        return
    
    # Step 3: Create OAuth2 configuration
    create_oauth_env_file()
    
    # Step 4: Install dependencies
    install_oauth_dependencies()
    
    # Step 5: Create summary
    create_migration_summary()
    
    print("=" * 50)
    print("🎉 Migration completed successfully!")
    print(f"📁 Backup created in: {backup_dir}")
    print("📖 Next steps in: MIGRATION_SUMMARY.md")
    print("⚠️  Remember to set up OAuth2 credentials before running the app!")

if __name__ == "__main__":
    main()
